/** Paths for Pump Farm HUD/UI asset pack (sliced from sheet). */

export const HUD = {
  panel: "/assets/sprites/ui/hud/panel_master.png",
  toast: "/assets/sprites/ui/hud/toast.png",
  progressFrame: "/assets/sprites/ui/hud/progress_frame.png",
  progressFill: "/assets/sprites/ui/hud/progress_fill.png",
  navFrame: "/assets/sprites/ui/hud/nav_frame.png",
  navFrameSelected: "/assets/sprites/ui/hud/nav_frame_selected.png",
  btnNormal: "/assets/sprites/ui/hud/btn_normal.png",
  btnHover: "/assets/sprites/ui/hud/btn_hover.png",
  btnPressed: "/assets/sprites/ui/hud/btn_pressed.png",
  pillFarm: "/assets/sprites/ui/hud/pill_farm.png",
  pillHype: "/assets/sprites/ui/hud/pill_hype.png",
  pillXp: "/assets/sprites/ui/hud/pill_xp.png",
  coin: "/assets/sprites/ui/hud/icon_coin.png",
  hype: "/assets/sprites/ui/hud/icon_hype.png",
  xp: "/assets/sprites/ui/hud/icon_xp.png",
  lock: "/assets/sprites/ui/hud/icon_lock.png",
  check: "/assets/sprites/ui/hud/icon_check.png",
  settings: "/assets/sprites/ui/hud/icon_settings.png",
  soundOn: "/assets/sprites/ui/hud/icon_sound_on.png",
  soundOff: "/assets/sprites/ui/hud/icon_sound_off.png",
  camera: "/assets/sprites/ui/hud/icon_camera.png",
  share: "/assets/sprites/ui/hud/icon_share.png",
  bag: "/assets/sprites/ui/hud/icon_bag.png",
  exit: "/assets/sprites/ui/hud/icon_exit.png",
  close: "/assets/sprites/ui/hud/icon_close.png",
  silo: "/assets/sprites/ui/hud/icon_silo.png",
  seed: "/assets/sprites/ui/hud/icon_seed.png",
  medal: "/assets/sprites/ui/hud/icon_medal.png",
  heart: "/assets/sprites/ui/hud/icon_heart.png",
  axe: "/assets/sprites/ui/hud/icon_axe.png",
} as const;
